version: "3.9"
services:
  reactapp:
    build:
      context: ./reactapp
    command: "npm run build"
    volumes: 
      - "./reactapp:/usr/src/app"
      - "/usr/src/app/node_modules"
  database:
    image: mariadb
    environment: 
      MYSQL_ROOT_PASSWORD: example
    ports:
      - 3306:3306
    volumes:
      - db:/var/lib/mysql
volumes:
  db: